// <auto-generated />
using System;
using ArtificeWorks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtificeWorks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArtificeWorksDbContext))]
    [Migration("20260723131830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.BomLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("QtyPerUnit")
                        .HasColumnType("bigint");

                    b.Property<string>("component_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("component_id");

                    b.HasIndex("ProductId", "component_id")
                        .IsUnique();

                    b.ToTable("bom_lines", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.Component", b =>
                {
                    b.Property<string>("ComponentId")
                        .HasColumnType("text");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OnHand")
                        .HasColumnType("bigint")
                        .HasColumnName("on_hand");

                    b.Property<long>("SeedOnHand")
                        .HasColumnType("bigint")
                        .HasColumnName("seed_on_hand");

                    b.HasKey("ComponentId");

                    b.ToTable("components", null, t =>
                        {
                            t.HasCheckConstraint("ck_components_on_hand_not_negative", "on_hand >= 0");
                        });
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.MaterialReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("material_reservations", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.MaterialReservationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("material_reservation_lines", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.Product", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.StockKeepingUnit", b =>
                {
                    b.Property<Guid>("SerialNumber")
                        .HasColumnType("uuid");

                    b.Property<int>("BuildAttempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BuiltUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InspectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScrapReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("product_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("work_order_id")
                        .HasColumnType("uuid");

                    b.HasKey("SerialNumber");

                    b.HasIndex("product_item_id");

                    b.HasIndex("work_order_id", "BuildAttempt");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Production.InspectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InspectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UnitsPassed")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsScrapped")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("inspection_runs", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Production.ProductionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BuiltUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UnitsBuilt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("production_runs", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Shipping.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DispatchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EstimatedArrivalUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Shipping.ShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SerialNumber")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_lines", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BuildAttempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderItemQty")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ordered_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Origin");

                    b.HasIndex("ordered_item_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.WorkOrderStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "ChangedUtc");

                    b.ToTable("work_order_state_history", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Infrastructure.Messaging.DeadLetters.DeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ParkedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReplayedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkedUtc");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("dead_letters", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_messages_unsent")
                        .HasFilter("\"SentUtc\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("ArtificeWorks.Infrastructure.Persistence.SimulationSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoBook")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoInspect")
                        .HasColumnType("boolean");

                    b.Property<double>("FailureRate")
                        .HasColumnType("double precision");

                    b.Property<bool>("GenerationEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("GenerationIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("MaxInFlight")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRebuildAttempts")
                        .HasColumnType("integer");

                    b.Property<double>("PaceJitter")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsInspectionPassed")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsMaterialsReserved")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsProductionCompleted")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsReworkRequired")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsScheduled")
                        .HasColumnType("double precision");

                    b.Property<double>("PaceSecondsShipmentScheduled")
                        .HasColumnType("double precision");

                    b.Property<bool>("PacingEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("RefusalRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RetireAfterHours")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorldSweepIntervalHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("simulation_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_simulation_settings_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.BomLine", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.Materials.Product", null)
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtificeWorks.Domain.Models.Materials.Component", "Component")
                        .WithMany()
                        .HasForeignKey("component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.MaterialReservation", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.MaterialReservationLine", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.Materials.MaterialReservation", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.StockKeepingUnit", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.Materials.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", null)
                        .WithMany("AssignedStock")
                        .HasForeignKey("work_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Production.InspectionRun", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Production.ProductionRun", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Shipping.Shipment", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Shipping.ShipmentLine", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.Shipping.Shipment", null)
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.WorkOrder", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.Materials.Product", "OrderedItem")
                        .WithMany()
                        .HasForeignKey("ordered_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderedItem");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.WorkOrderStateHistory", b =>
                {
                    b.HasOne("ArtificeWorks.Domain.Models.WorkOrder", "WorkOrder")
                        .WithMany("StateHistory")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.MaterialReservation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Materials.Product", b =>
                {
                    b.Navigation("BillOfMaterials");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.Shipping.Shipment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ArtificeWorks.Domain.Models.WorkOrder", b =>
                {
                    b.Navigation("AssignedStock");

                    b.Navigation("StateHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
