import { Link } from "react-router-dom";

import { eventMeta } from "../domain/events";
import { useRealtime, type FeedEntry } from "../realtime/RealtimeProvider";
import { absoluteTime, relativeTime } from "../util/time";

/**
 * The live event feed (11.2): real broker traffic, newest-first, as it happens — every published
 * work-order.* event, including the faulted/completed announcements the pipeline never consumes. It
 * is a tail, not a log; history lives in the dead-letter view and the traces. Each line is tagged
 * visitor vs robot when the board has told us which the order is.
 */
export function EventFeed() {
  const { feed } = useRealtime();
  // One clock per render, so every line's relative time is consistent within a tick.
  const now = Date.now();

  return (
    <aside className="feed" aria-label="Live event feed">
      <header className="feed-header">
        <span className="feed-title">Event feed</span>
        <span className="feed-sub">real broker traffic</span>
      </header>
      {feed.length === 0 ? (
        <p className="feed-empty">Waiting for the factory to say something…</p>
      ) : (
        <ol className="feed-list">
          {feed.map((entry) => (
            <FeedRow key={entry.key} entry={entry} now={now} />
          ))}
        </ol>
      )}
    </aside>
  );
}

function FeedRow({ entry, now }: { entry: FeedEntry; now: number }) {
  const meta = eventMeta(entry.eventType);
  const originClass = entry.origin ? `feed-origin-${entry.origin.toLowerCase()}` : "";

  return (
    <li className={`feed-row tone-${meta.tone}`}>
      <div className="feed-row-top">
        <span className={`feed-label tone-${meta.tone}`}>{meta.label}</span>
        {entry.origin && (
          <span
            className={`feed-origin ${originClass}`}
            title={entry.origin === "Visitor" ? "Requested by a visitor" : "Generated by the simulation"}
          >
            {entry.origin === "Visitor" ? "🧑" : "🤖"}
          </span>
        )}
        <time className="feed-time" dateTime={entry.occurredUtc} title={absoluteTime(entry.occurredUtc)}>
          {relativeTime(entry.occurredUtc, now)}
        </time>
      </div>
      <div className="feed-row-sub">
        {entry.workOrderId ? (
          <Link className="feed-order" to={`/orders/${entry.workOrderId}`} title={entry.workOrderId}>
            {entry.workOrderId.slice(0, 8)}
          </Link>
        ) : (
          <span className="feed-order feed-order-none">—</span>
        )}
        <code className="feed-correlation" title={`correlation ${entry.correlationId}`}>
          {entry.correlationId.slice(0, 8)}
        </code>
      </div>
    </li>
  );
}
