import type { WorkOrderOrigin } from "../api/types";

/**
 * A visitor order vs a robot's, at a glance — the distinction 10.3 built the Origin column for.
 * A visitor asked for it (person); the simulation's generator asked for the other (robot).
 */
export function OriginBadge({ origin }: { origin: WorkOrderOrigin }) {
  const isVisitor = origin === "Visitor";
  return (
    <span
      className={`origin-badge origin-${origin.toLowerCase()}`}
      title={isVisitor ? "Requested by a visitor" : "Generated by the simulation"}
    >
      <span aria-hidden="true">{isVisitor ? "🧑" : "🤖"}</span>
      {isVisitor ? "Visitor" : "Robot"}
    </span>
  );
}
